config/routes.rb
Rails.application.routes.draw do

  get 'students_home/index'
  get 'students_home/profile'
  root 'home#index'
  get 'students/import_sample'
  get 'students/delete_all' => 'students#delete_all'
  get 'students/view' => 'students#view'
  get 'students_home/password_reset'
  get 'voucher_mappings/bulk_download'
  get 'voucher_mappings/download_csv'
  get 'voucher_mappings/delete_all'
  get 'letters/day_scholar_letter'
  get 'letters/boarder_letter'
  get 'coaching_sessions/index'
  get 'undertakings/pending'
  get 'undertakings/upload'
  get 'undertakings/manage'
  get 'undertakings/accepted_view'
  get 'undertakings/downloaded_view'
  get "voucher_nos/update_it"
  get "activate_coaching_sessions" => "coaching_sessions#activate"
  get 'students/:id/view' => 'students#index'
  get 'letters/index'
  get 'students_home/profile'
  devise_for :users, controllers: { registrations: "registrations"}
  resources :coaching_sessions
  resources :letters
  resources :students_home
  resources :students do
    collection { post :import }
  end
  resources :voucher_mappings do
    collection { post :import }
  end
  resources :home
  resources :undertaking_texts
  resources :undertakings

  match ':controller(/:action(/:id))', :via => [:get, :post]
end

app/models/student.rb
class Student < ActiveRecord::Base
    require 'roo'
    has_secure_password
    def self.to_csv(options = {})
      CSV.generate(options) do |csv|
          csv << column_names
          all.each do |student|
              csv << student.attributes.values_at(*column_names)
          end
      end
    end
    def self.import(file)
        spreadsheet = open_spreadsheet(file)
        if spreadsheet
            header = spreadsheet.row(1)
            (2..spreadsheet.last_row).each do |i|
                row = Hash[[header, spreadsheet.row(i)].transpose]
                student = find_by_tracking_id(row["tracking_id"]) || new
                student.attributes = row.to_hash.slice(*row.to_hash.keys)
                student.session = CoachingSession.where(:status => true).take.name
                if student.city
                    if student.city.titleize().strip=="Lahore"
                        student.boarder = false
                    else
                        student.boarder = true
                    end
                end
                
                student.secondary_tracking = student.password
                # begin
                    student.save!
                    User.create!(:email => student.username,:password => student.password,:role => "student")
                # rescue 
                # end
            end
        end
        
        
    end
    
    def self.open_spreadsheet(file)
        if file
            case File.extname(file.original_filename)
            when ".csv" then Csv.new(file.path, nil, :ignore)
            when ".xls" then Excel.new(file.path, nil, :ignore)
            when ".xlsx" then Roo::Excelx.new(file.path, packed: nil, file_warning: :ignore)
            else raise "Unknown file type: #{file.original_filename}"
            end
        end
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authorize_admin
  
  skip_before_action :authorize_admin, only: [:show]
  def index
    if params[:sort]

      @students=Student.order(params[:sort] + ' ' + params[:direction])
      @active_session = CoachingSession.where(:status => true).take
      @students = @students.where(:session => @active_session.name)
      @count = @students.count
      @link = "students_view"
    else
      @students = Student.all
      @active_session = CoachingSession.where(:status => true).take
      @students = @students.where(:session => @active_session.name)
      @count = @students.count
      @link = "students_view"
    end
    if params[:admin] == "view_student"
      @student=Student.find(params[:id])
      @link = "view_student"
    end
      
    
  end
  def show
    @student=Student.find(params[:id])
    @active_session = CoachingSession.where(:status => true).take
    
    begin
      Tracking.create(:session => @active_session.name,:downloaded => true,:name => @student.name,:tracking_id => @student.tracking_id)
    rescue
    end
    
    @voucher=VoucherMapping.find_by_tracking_id(params[:id])
    if @voucher
      fee_voucher = FeeVoucher.find_by_voucher_no(@voucher.voucher_no)
      if not fee_voucher
        student = Student.find_by_tracking_id(params[:id])
        FeeVoucher.create(:name => student.name , :voucher_no => @voucher.voucher_no , :tracking_id => student.tracking_id , :total_amount => "2200" ,:payment_deadline => "20160629",:status => "unpaid")
      end
    else
      voucher=VoucherNo.last
      voucher_no_old = voucher.voucher_no
      voucher_no_new = voucher_no_old.to_i + 1
      voucher_no_new = voucher_no_new.to_s
      VoucherNo.last.destroy
      VoucherNo.create(:voucher_no => voucher_no_new)
      VoucherMapping.create(:session => @active_session.name, :voucher_no => voucher_no_old,:tracking_id => @student.tracking_id)
      student = Student.find_by_tracking_id(params[:id])
      FeeVoucher.create(:name => student.name , :voucher_no => voucher_no_old , :tracking_id => student.tracking_id , :total_amount => "2200" ,:payment_deadline => "June 29,2016",:status => "unpaid" , :mobile_number => student.mobile_number , :email => student.email , :phone_number => student.phone_number)
      
    end
    @voucher=VoucherMapping.find_by_tracking_id(params[:id])
    
    respond_to do |format|
        format.html
        format.pdf do
            pdf = StudentVoucherPdf.new(@student,@active_session,@voucher)
            send_data pdf.render, filename: "#{@student.name}'s voucher'.pdf", type: "application/pdf", disposition: "inline"
        end
    end
  end
  def new
    @student = Student.new
  end
  def view
    @student=Student.find(params[:id])
  end
  def create
    @student = Student.new(student_params)
    @active_session = CoachingSession.where(:status => true).take
    @student.session = @active_session.name
    if @student.city
      if @student.city.titleize()=="Lahore"
          @student.boarder = false
      else
          @student.boarder = true
      end
    end
    respond_to do |format|
      if @student.save
        User.create!(:email => @student.username,:password => @student.password,:role => "student")
        # @name = CoachingSession.where(:status => true).take.name
        # Undertaking.create!(:tracking_id => params[:id],:data => Null,:via => "Mail",:session => @name,:admin_status => false,:status => false)
        flash[:notice] = 'Student was successfully created.'
        format.html { redirect_to students_path}
        format.json { render :show, status: :created, location: @student }
      else
     #   redirect_to new_student_path
        format.html { render :new }
        format.json {  render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end
  def edit
    @student=Student.find(params[:id])
  end
  def update
    @student=Student.find(params[:id])
    @user = User.find_by_email(@student.username)
      respond_to do |format|
        begin
          @student.update(student_params)
          
          @user.update(:password => @student.password,:email => @student.username)
          format.html { redirect_to students_path, notice: 'Student was successfully updated.' }
          format.json { render :show, status: :ok, location: @student }
        rescue
          format.html { render :edit }
          format.json { render json: @student.errors, status: :unprocessable_entity }
        end
      end
  end
  def delete_all
    # begin
      @students=Student.where(:session => CoachingSession.where(:status => true).take.name)
      @students.each do |student|
        user = User.where(:email => student.username).take
        student.destroy
        user.destroy
      end
      flash[:notice] = 'All Students were successfully destroyed.'
      redirect_to :controller => "students",:action => "index"
    # rescue
    # end
  end
  def destroy
    @student=Student.find(params[:id])
    @user = User.where(:email => @student.username).take
    @student.destroy
    @user.destroy
    respond_to do |format|
      # format.html { redirect_to students_url}
      format.html { redirect_to students_path }
      
      flash[:notice] = 'Student was successfully destroyed.'
      format.json { head :no_content }
    end
  end
  def import
    Student.import(params[:file])
    redirect_to students_path, notice: "Students imported"
  end
  def import_sample
  end
  def export
    package = Axlsx::Package.new
    workbook = package.workbook
    workbook.add_worksheet(name: "Basic work sheet") do |sheet|
      sheet.add_row ["stream", "tracking_id","name", "father_name","m_o_level_stream","graduation_year","o_level_grades", "matric_percentage", "DOB", "gender","address1","address2","address3", "city","district","province","phone_number", "mobile_number", "monthly_income","income_range","session","boarder","email", "username"]
      @students=Student.all
      @active_session = CoachingSession.where(:status => true).take
      @students = @students.where(:session => @active_session.name)
      @students.each do |st|
        sheet.add_row [st.stream, st.tracking_id,st.name, st.father_name,st.m_o_level_stream,st.graduation_year,st.o_level_grades, st.matric_percentage,st.DOB,st.gender,st.address1,st.address2,st.address3, st.city,st.district,st.province,st.phone_number,st.mobile_number,st.monthly_income,st.income_range, st.session,st.boarder,st.email,st.username]
      end
    end
    send_data package.to_stream.read, :filename => "students.xlsx"
  end
  def export_sample
    package = Axlsx::Package.new
    workbook = package.workbook
    workbook.add_worksheet(name: "Basic work sheet") do |sheet|
      sheet.add_row ["stream", "tracking_id","name", "father_name","m_o_level_stream","graduation_year","o_level_grades", "matric_percentage", "DOB", "gender","address1","address2","address3", "city","district","province","phone_number", "mobile_number", "monthly_income","income_range","boarder","email", "username","password"]
    end
    send_data package.to_stream.read, :filename => "students.xlsx"
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def student_params
    params.require(:student).permit( :name,:father_name,:tracking_id, :session,:stream,:m_o_level_stream,:graduation_year,:matric_percentage,:o_level_grades,:DOB,:gender,:address1,:address2,:address3,:city,:district,:province,:mobile_number,:phone_number,:monthly_income,:income_range,:boarder, :email, :username, :password)
  end  
  
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/edit.html.erb
<div class = "animated fadeIn">
<div id="content">
<header>
  <strong><class="page_title">Edit <%= @student.name %>'s Information</strong>
  <%= link_to "Return Without Saving", students_path, :class => "btn btn-xs btn-primary pull-right", :role => "button" %>
</header>
<div class="content-inner">
  <div class="form-wrapper">
      <%= bootstrap_form_for @student do |f| %>
        <%= f.errors_on :name %>
          <%= f.text_field :stream, label: "Stream" %>
          <%= f.text_field :name, label: "Name", :required => true%>
          <%= f.text_field :tracking_id, label: 'NOP Tracking ID', :required => true %>
          <%= f.text_field :father_name, label: 'Father Name', :required => true %>
          <%= f.text_field :DOB, label: 'Date of Birth', :required => true, help: "Be Careful! Enter date in dd/mm/yyyy pattern only" %>
          <%= f.select :gender,[["Select:", "?"],["Male", "M"], ["Female", "F"]],{ label: "Gender" },{ class: "selectpicker" }    %>
          <%= f.text_field :m_o_level_stream, label: "Matric/O-Level Stream" %>
          <%= f.text_field :matric_percentage, label: "Matric Percentage" %>
          <%= f.text_field :o_level_grades, label: "O-Level Grades" %>
          <%= f.number_field :monthly_income, label: "Monthly income", :required => true %>
          <%= f.text_field :income_range, label: "Income Range" %>
          <%= f.text_field :address1, label: "Address Line 1" %>
          <%= f.text_field :address2, label: "Address Line 2" %>
          <%= f.text_field :address3, label: "Address Line 3" %>
          <%= f.text_field :city, label: 'City' %>
          <%= f.text_field :district, label: 'District' %>
          <%= f.text_field :province, label: 'Province' %>
          <%= f.select :boarder, [["Select:"],["Boarder", true], ["Day Scholar", false]], { label: "Boarder" },{ class: "selectpicker" } %>
          <%= f.email_field :email, label: 'Email Address' %>
          <%= f.text_field :mobile_number, label: 'Mobile Number' %>
          <%= f.text_field :phone_number, label: 'Phone Number' %>
          <%= f.email_field :username, label: 'Username', :required => true  %>
          <%= f.text_field :password, label: 'Password', :required => true  %>
        <div class="clearfix" type = "submit">
          <%= f.submit  %>
          <% end %>
        </div>
    </form>
  </div>
</div>
</div> 

app/views/students/import_sample.html.erb
<div class="admin-content-con">
    <br>
    <%= form_tag :controller => :students, :action => :export_sample do %>
        <%= submit_tag "Download sample file", class: "btn btn-xs btn-primary pull-left", id: "export" %>
    <% end %> 
    <br><br>
    <%= form_tag import_students_path, multipart: true do %>
        <%= file_field_tag :file %>
        <br>
        <%= submit_tag "Import" %>
    <% end %>
</div>

app/views/students/index.html.erb
<% if @link == "students_view" %>
<div class = "animated fadeIn" ng-app="Studentsr" ng-controller="StudentCtrl">
  <div id="dashboard-con">
    <div>
      <ng-view></ng-view>
      <div class="dashboard-left-cell">
        <div class="admin-content-con">
          <header class="clearfix">
            <strong><h5 class="pull-left page_title">All Students : <%= @count %></h5></strong>
            <div class = "divider pull-right">
              <%= link_to "Add new student", new_student_path, :class => "btn btn-xs btn-primary pull-right", :role => "button" %> 
            </div>
            <div class = "divider pull-right">
              <%= link_to "Delete All Students", url_for(:controller => :students, :action => :delete_all), :class => "btn btn-xs btn-primary pull-right", :role => "button", :data => {confirm: 'Are you sure you want to delete all students?'}  %> 
            </div>
            <div class = "divider pull-right">
              <%= form_tag :controller => :students, :action => :export do %>
                <%= submit_tag "Download in Excel", class: "btn btn-xs btn-primary pull-right", id: "export" %>
              <% end %>
            </div>
            <div class = "divider pull-right">
              <%= link_to "Import from Excel", url_for(:controller => :students, :action => :import_sample), :class => "btn btn-xs btn-primary pull-right", :role => "button" %> 
            </div>
            <div class="col-sm-2 pull-right lil">
            <input type="text" class="form-control-special" ng-model="searchString" placeholder="Search Students"/>
            </div>
           
          </header>
          <table class="table table-striped">
            <thead>
              <tr>
                <th><%= sortable "Name" %><span class="glyphicon glyphicon-sort-by-order" aria-hidden="true"></th>
                <th><%= sortable "tracking_id" %><span class="glyphicon glyphicon-sort-by-order" aria-hidden="true"></th>
                <th><%= sortable "monthly_income" %><span class="glyphicon glyphicon-sort-by-order" aria-hidden="true"></th>
                <th>City</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <tr ng-repeat="student in students | searchFor:searchString">
                  <td>{{student.name}}</td>
                  <td>{{student.tracking_id}}</td>
                  <td>{{student.monthly_income}}</td>
                  <td>{{student.city}}</td>
                  <td>
                    <%= link_to 'Edit', URI::unescape(edit_student_path(:id => '{{student.tracking_id}}')), :class => 'btn btn-xs btn-warning', :role => "button" %>
                    <%= link_to 'View', URI::unescape(students_path(:id => '{{student.tracking_id}}',:admin => "view_student")), :class => 'btn btn-xs btn-primary', :role => "button" %>
                    <%= link_to 'Delete', URI::unescape('students/{{student.tracking_id}}'), method: :delete, :class => 'btn btn-xs btn-danger', :role => "button", :data => {confirm: 'Are you sure you want to delete this?'} %>
                  </td>
              </tr>
            </tbody>
          </table>
          
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  var stdMod = angular.module('Studentsr', []); 
  stdMod.controller('StudentCtrl', function ($rootScope, $http) {
    $rootScope.students = []
    <% if @students!=nil%>
      <% @students.each do |student| %>
        $rootScope.students.push({
          name:'<%= student.name.titleize() %>',
          tracking_id: '<%= student.tracking_id %>',
          monthly_income: '<%= student.monthly_income %>',
          <% if student.city %>
           city: '<%= student.city.titleize() %>'
          <% else %>
           city: '<%= student.city %>'
          <% end %>
        })
    <% end %>
  <% end %>
  });
  stdMod.filter('searchFor', function(){
  return function(arr, searchString){
    if(!searchString){
      return arr;
    }
    var result = [];
    searchString = searchString.toLowerCase();
    angular.forEach(arr, function(item){
      if(item.name.toLowerCase().indexOf(searchString) !== -1){
        result.push(item);
      }else if(item.tracking_id.toLowerCase().indexOf(searchString) !== -1){
        result.push(item);
      }else if(item.monthly_income.toLowerCase().indexOf(searchString) !== -1){
        result.push(item);
      }else if(item.city.toLowerCase().indexOf(searchString) !== -1){
        result.push(item);
      }
    });
    return result;
  };
  });
</script>
<% end %>

<% if @link == "view_student" %>
    <div class = "animated fadeIn">
      <div id="dashboard-con">
        <div>
          <div class="dashboard-left-cell">
            <div class="admin-content-con">
              <header class="clearfix">
                <strong><h3 class="pull-left page_title"><%= @student.name %>'s details</h3></strong>
                <div class = "divider pull-right">
                 <%= link_to "All Students", students_path, :class => "btn btn-xs btn-primary pull-right", :role => "button" %>
              </header>
                <strong>Stream:</strong>&nbsp;&nbsp;&nbsp;<%= @student.stream %><hr/>
                <strong>Tracking ID:</strong>&nbsp;&nbsp;&nbsp;<%= @student.tracking_id %><hr/>
                <strong>Name:</strong>&nbsp;&nbsp;&nbsp;<%= @student.name %><hr/>
                <strong>Father's Name:</strong>&nbsp;&nbsp;&nbsp;<%= @student.father_name %><hr/>
                <strong>Matric/O-Level Stream:</strong>&nbsp;&nbsp;&nbsp;<%= @student.m_o_level_stream %><hr/>
                <strong>Graduation year:</strong>&nbsp;&nbsp;&nbsp;<%= @student.graduation_year %><hr/>
                <strong>Date of Birth:</strong>&nbsp;&nbsp;&nbsp;<%= @student.DOB %><hr/>
                <strong>Gender:</strong>&nbsp;&nbsp;&nbsp;<%= @student.gender %><hr/>
                <strong>Matric Percentage:</strong>&nbsp;&nbsp;&nbsp;<%= @student.matric_percentage %><hr/>
                <strong>O-Level Grades:</strong>&nbsp;&nbsp;&nbsp;<%= @student.o_level_grades %><hr/>
                <strong>Address 1:</strong>&nbsp;&nbsp;&nbsp;<%= @student.address1 %><hr/>
                <strong>Address 2:</strong>&nbsp;&nbsp;&nbsp;<%= @student.address2 %><hr/>
                <strong>Address 3:</strong>&nbsp;&nbsp;&nbsp;<%= @student.address3 %><hr/>
                <strong>City:</strong>&nbsp;&nbsp;&nbsp;<%= @student.city %><hr/>
                <strong>District:</strong>&nbsp;&nbsp;&nbsp;<%= @student.district %><hr/>
                <strong>Province:</strong>&nbsp;&nbsp;&nbsp;<%= @student.province %><hr/>
                <strong>Mobile number:</strong>&nbsp;&nbsp;&nbsp;<%= @student.mobile_number %><hr/>
                <strong>Phone number:</strong>&nbsp;&nbsp;&nbsp;<%= @student.phone_number %><hr/>
                <strong>Boarder:</strong>&nbsp;&nbsp;&nbsp;<%= @student.boarder %><hr/>
                <strong>Session:</strong>&nbsp;&nbsp;&nbsp;<%= @student.session %><hr/>
                <strong>Email Address:</strong>&nbsp;&nbsp;&nbsp;<%= @student.email %><hr/>
                <strong>Monthly Income:</strong>&nbsp;&nbsp;&nbsp;<%= @student.monthly_income %><hr/>
                <strong>Income Range:</strong>&nbsp;&nbsp;&nbsp;<%= @student.income_range %><hr/>
                <strong>DataBurj Username:</strong>&nbsp;&nbsp;&nbsp;<%= @student.username %>
            </div>
          </div>
        </div>
      </div>
<% end %>
  

app/views/students/new.html.erb
 <div class = "animated fadeIn">
  <div id="content">
    <header>
      <strong><class="page_title">Add new student</strong>
      <%= link_to "Return Without Saving", students_path, :class => "btn btn-xs btn-primary pull-right", :role => "button" %>
    </header>
    <div class="content-inner">
      <div class="form-wrapper">
        <%= bootstrap_form_for Student.new do |f| %>
          <%= f.errors_on :name %>
          <%= f.text_field :stream, label: "Stream" %>
          <%= f.text_field :name, label: "Name", :required => true%>
          <%= f.text_field :tracking_id, label: 'NOP Tracking ID', :required => true %>
          <%= f.text_field :father_name, label: 'Father Name', :required => true %>
          <%= f.text_field :DOB, label: 'Date of Birth', :required => true, help: "Be Careful! Enter date in dd/mm/yyyy pattern only" %>
          <%= f.select :gender,[["Select:", "?"],["Male", "M"], ["Female", "F"]],{ label: "Gender" },{ class: "selectpicker" }    %>
          <%= f.text_field :m_o_level_stream, label: "Matric/O-Level Stream" %>
          <%= f.text_field :matric_percentage, label: "Matric Percentage" %>
          <%= f.text_field :o_level_grades, label: "O-Level Grades" %>
          <%= f.number_field :monthly_income, label: "Monthly income", :required => true %>
          <%= f.text_field :income_range, label: "Income Range" %>
          <%= f.text_field :address1, label: "Address Line 1" %>
          <%= f.text_field :address2, label: "Address Line 2" %>
          <%= f.text_field :address3, label: "Address Line 3" %>
          <%= f.text_field :city, label: 'City' %>
          <%= f.text_field :district, label: 'District' %>
          <%= f.text_field :province, label: 'Province' %>
          <%= f.select :boarder, [["Select:"],["Boarder", true], ["Day Scholar", false]], { label: "Boarder" },{ class: "selectpicker" } %>
          <%= f.email_field :email, label: 'Email Address' %>
          <%= f.text_field :mobile_number, label: 'Mobile Number' %>
          <%= f.text_field :phone_number, label: 'Phone Number' %>
          <%= f.email_field :username, label: 'Username', :required => true  %>
          <%= f.text_field :password, label: 'Password', :required => true  %>
          <div class="clearfix" type = "submit">
            <%= f.submit  %>
        <% end %>
          </div>
        </form>
      </div>
    </div>
  </div>