config/routes.rb
Rails.application.routes.draw do

  get 'students_home/index'
  get 'students_home/profile'
  root 'home#index'
  get 'students/import_sample'
  get 'students/delete_all' => 'students#delete_all'
  get 'students/view' => 'students#view'
  get 'students_home/password_reset'
  get 'voucher_mappings/bulk_download'
  get 'voucher_mappings/download_csv'
  get 'voucher_mappings/delete_all'
  get 'letters/day_scholar_letter'
  get 'letters/boarder_letter'
  get 'coaching_sessions/index'
  get 'undertakings/pending'
  get 'undertakings/upload'
  get 'undertakings/manage'
  get 'undertakings/accepted_view'
  get 'undertakings/downloaded_view'
  get "voucher_nos/update_it"
  get "activate_coaching_sessions" => "coaching_sessions#activate"
  get 'students/:id/view' => 'students#index'
  get 'letters/index'
  get 'students_home/profile'
  devise_for :users, controllers: { registrations: "registrations"}
  resources :coaching_sessions
  resources :letters
  resources :students_home
  resources :students do
    collection { post :import }
  end
  resources :voucher_mappings do
    collection { post :import }
  end
  resources :home
  resources :undertaking_texts
  resources :undertakings

  match ':controller(/:action(/:id))', :via => [:get, :post]
end

app/models/coaching_session.rb
class CoachingSession < ActiveRecord::Base
   validates :name, presence: true, uniqueness: true
end

app/controllers/coaching_sessions_controller.rb
class CoachingSessionsController < ApplicationController
   skip_before_action :require_session, :only => [:index, :new,:create,:update,:edit,:delete,:destroy,:activate]
   before_action :authorize_admin
    def index
        @coaching_sessions= CoachingSession.all
    end
    def new
        @coaching_session= CoachingSession.new
    end
    def create
        @coaching_session = CoachingSession.new(coaching_session_params)
        respond_to do |format|
          if @coaching_session.save
            format.html { redirect_to url_for(:controller => :coaching_sessions), notice: 'Session was successfully created.' }
            format.json { render :show, status: :created, location: @coaching_session }
          else
            format.html { render :new }
            format.json { render json: @coaching_session.errors, status: :unprocessable_entity }
          end
        end
    end
    def edit
        @coaching_session=CoachingSession.find(params[:id])
    end
    def update
        @coaching_session=CoachingSession.find(params[:id])
        respond_to do |format|
            if @coaching_session.update(coaching_session_params)
                format.html { redirect_to url_for(:controller => :coaching_sessions), notice: 'Session was successfully updated' }
                format.json { render :show, status: :ok, location: @coaching_session }
            else
                format.html { render :edit }
                format.json { render json: @coaching_session.errors, status: :unprocessable_entity }
            end
        end
    end
    def delete
        @coaching_session=CoachingSession.find(params[:id])
    end
    def destroy
        @coaching_session=CoachingSession.find(params[:id])
        @coaching_session.destroy
        respond_to do |format|
          format.html { redirect_to url_for(:controller => :coaching_sessions), notice: 'Session was successfully destroyed' }
          format.json { head :no_content }
        end
    end
    def activate
        @coaching_session=CoachingSession.find(params[:id])
        if @coaching_session.status
            @coaching_session.update(:status => false)
        else
            @active = CoachingSession.where(:status => true).take
            if @active
                @active.update(:status => false)
            end
            if @coaching_session
                @coaching_session.update(:status => true)
            end
        end
        redirect_to url_for(:controller => :coaching_sessions), notice: 'Session was successfully updated'
    end
    def coaching_session_params
      params.require(:coaching_session).permit(:coaching_session_id, :name,:status )
    end
end

app/helpers/coaching_sessions_helper.rb
module CoachingSessionsHelper
end

app/views/coaching_sessions/index.html.erb
 <div id="dashboard-con">
   
    <div class="row">
      <div class="col-md-6 dashboard-left-cell">
        <div class="admin-content-con">
          <header class="clearfix">
            <h5 class="pull-left">All Sessions</h5>
          </header>
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Name</th>
                <th>Status</th>
                <th>actions</th>
              </tr>
            </thead>
            <tbody>
              <% @coaching_sessions.each do |coaching_session| %>
                <tr>
                  <td><%= coaching_session.name %></td>
                  <td><%= coaching_session.status %></td>
                  <td>
                    <% if coaching_session.status %>
                    <%= link_to 'Deactivate', activate_coaching_sessions_path( :id => coaching_session.id), :class => 'btn btn-xs btn-primary', :role => "button" %>
                    <% else %>
                     <%= link_to 'Activate', activate_coaching_sessions_path( :id => coaching_session.id), :class => 'btn btn-xs btn-primary', :role => "button" %>
                    <% end %>
                    <%= link_to 'Delete', coaching_session, method: :delete, :class => 'btn btn-xs btn-danger', :role => "button", :data => {confirm: 'Are you sure you want to delete this?'} %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>

        </div>
      </div>
      <% @current_session = CoachingSession.where(:status => true).take %>
      <div class="col-md-6 dashboard-right-cell">
        <div class="admin-content-con">
          <header>
            <h5>Add New Session</h5>
          </header>
          <div class="content-inner">
            <div class="form-wrapper">
              <%= bootstrap_form_for CoachingSession.new do |f| %>
                <%= f.errors_on :coaching_session %>
                <%= f.text_field :name, label: "Session Year", :required => true%>
                <div class="clearfix" type = "submit">
                  <%= f.submit %>
                  <% end %>
                </div>
              </form>
            </div>
          </div>
        </div>
  </div>
</div>

    <div class="row">
      <div class="col-md-12">
        <div class="admin-content-con clearfix">
          <header>
            <strong><h5>Active Session</h5></strong>
          </header>
          <% if @current_session %>
            Current Active session is <%= @current_session.name %>
          <% else %>
            Currently no session is active.
          <% end %>
        </div>
      </div>
    </div>
  </div>