config/routes.rb
Rails.application.routes.draw do

  get 'students_home/index'
  get 'students_home/profile'
  root 'home#index'
  get 'students/import_sample'
  get 'students/delete_all' => 'students#delete_all'
  get 'students/view' => 'students#view'
  get 'students_home/password_reset'
  get 'voucher_mappings/bulk_download'
  get 'voucher_mappings/download_csv'
  get 'voucher_mappings/delete_all'
  get 'letters/day_scholar_letter'
  get 'letters/boarder_letter'
  get 'coaching_sessions/index'
  get 'undertakings/pending'
  get 'undertakings/upload'
  get 'undertakings/manage'
  get 'undertakings/accepted_view'
  get 'undertakings/downloaded_view'
  get "voucher_nos/update_it"
  get "activate_coaching_sessions" => "coaching_sessions#activate"
  get 'students/:id/view' => 'students#index'
  get 'letters/index'
  get 'students_home/profile'
  devise_for :users, controllers: { registrations: "registrations"}
  resources :coaching_sessions
  resources :letters
  resources :students_home
  resources :students do
    collection { post :import }
  end
  resources :voucher_mappings do
    collection { post :import }
  end
  resources :home
  resources :undertaking_texts
  resources :undertakings

  match ':controller(/:action(/:id))', :via => [:get, :post]
end

app/controllers/students_home_controller.rb
class StudentsHomeController < ApplicationController
  def index
    @student=Student.find_by_username(current_user.email)
    tracking = Tracking.find_by_tracking_id(@student.tracking_id)
    if tracking
      @link = "download"
    else
      @link = "default"
    end
  end

  def profile
    @student=Student.find_by_username(current_user.email)
  end
  def accept_undertaking
      begin
          student = Student.find(params[:id])
          active_session = CoachingSession.where(:status => true).take.name
          Tracking.create(:session => active_session,:tracking_id => params[:id],:name => student.name,:accepted => true)
          flash[:notice] = "Undertaking accepted"
          redirect_to :controller => "students_home",:action => "index"
      rescue
          redirect_to :controller => "students_home",:action => "index"
      end
  end
  def password_reset
  end
  def reset
    @user = current_user
    if params[:new_password] == params[:confirm_password]
      @user.update(:password => params[:new_password])
    else
      flash[:notice]="password and confirm password don't match. confirm again"
      redirect_to :controller => "students_home",:action => "password_reset"
    end
  end
end

app/helpers/students_home_helper.rb
module StudentsHomeHelper
end

app/views/students_home/index.html.erb
<% if @link == "download" %>
<div id="dashboard-con">
    <div class="admin-content-con">
        <div id = "btext">
            Last date for submission of security/laundry dues – 29th June 2016<br/>
            Last date for uploading a scanned copy of the paid voucher – 30th June 2016<br/>
            Last date for acceptance of invitation (online or by post) – 30th June 2016<br/>
        </div>
    </div>
    <div class="admin-content-con">
        <div class = "divider pull-right">
            <%= link_to "My Profile", url_for(:controller => "students_home", :action => "profile"),  :class => "btn btn-primary", :role => "button"  %> 
        </div>
        Download Fee Voucher<br/><br/>
        <%= link_to "Download Fee Voucher", student_path(@student, format: "pdf"), target: "_blank", :class => "btn btn-primary", :role => "button" %> 
        <hr/>Upload Fee Receipt<br/><br/>
        <%= link_to "Upload Fee Voucher", url_for(:controller => "undertakings", :action => "upload"),  :class => "btn btn-primary", :role => "button"  %>
        <%= link_to "View Uploaded Fee Voucher", url_for(:controller => "undertakings", :action => "displayfile", id: Student.where(:username => current_user.email).take.tracking_id),target: "_blank",  :class => "btn btn-primary", :role => "button"  %>
    </div>
    <div class="admin-content-con">
        
        <div class="footers">
          <div id = "ptext">
            <b>  In case of any query contact the following personnel before the deadline 
                Sadia Babar: 042-35608262/ Sharjeel Muazzam: 042-35608438/ Momin Sharif: 042-35608000 (Ext. 2419)/ Shajia Shoaib: 042-35608204
            </b>
          </div>
          
       </div>
        
        
        
    </div>
</div>






<% else %>

    <div id = "btext">
        Last date for submission of security/laundry dues – 29th June 2016<br/>
        Last date for uploading a scanned copy of the paid voucher – 30th June 2016<br/>
        Last date for acceptance of invitation (online or by post) – 30th June 2016<br/>
    	<!--<h1>IDEABOX - Multipurpose Step Form.js</h1>-->
        <!--<h2>A clean, basic, flat, full responsive, mobile friendly, form validate and multipurpose step form</h2>-->
    </div>
    
    <div class="containers">
    	<div class="container-tops">
        	
        
        <!--STEPS FORM START ------------ -->
        <div class="stepsForm">
            <form method="post">
                <div class="sf-steps">
                    <div class="sf-steps-content">
                    	<div>
                        	<span>1</span> Instructions
                        </div>
                        <div>
                        	<span>2</span> Offer Letter
                        </div>
                        <div>
                        	<span>3</span> Undertaking
                        </div>
                        <div>
                        	<span>4</span> Voucher Download
                        </div>
                    </div>
                </div>                
                <div class="sf-steps-form sf-radius"> 
                    
                    <ul class="sf-content"> <!-- form step one --> 
                         <li>
                            <div class="sf_columns column_6">
                                <label class="sf-select">

                                	<ol>
                                        <li><p align = "left">Read the Instructions carefully.</p></li>
                                        <li><p align = "left">Under the <b>Offer Letter</b> Tab, read the letter and check mark the box at the bottom, then press the next button.</p</li>
                                        <li><p align = "left">In Undertaking Tab, clearly read out the undertaking/ confirmations and check mark the box below as your acknowledgement, then press the next button.</p></li>
                                        <li><p align = "left">In Fee Voucher Tab download a copy of your fee payment voucher(in case you are living outside Lahore).</p></li>
                                        <li><p align = "left">Pay the requisite amount in any ABL branch</p></li>
                                        <li><p align = "left">Under the same Fee Voucher tab, upload a scanned copy of your paid fee voucher.</p></li>
                                        <li><p align = "left">This ends your online registration process.</p></li>
                                    
                                    </ol>
                                
                                </label>
                    <%= link_to "My Profile", url_for(:controller => "students_home", :action => "profile"),  :class => "btn btn-primary", :role => "button"  %>            
                            </div>
                         </li>
                    </ul>
                       
                    <ul class="sf-content"> <!-- form step two --> 
                         <li>
                            <div class="sf_columns column_6">
                                <div id = "utext">
                                <% if @student.boarder == true %>
                                <%= raw Letter.find(1).boarder_letter_text %>
                                <% else %>
                                <%= raw Letter.find(1).day_scholar_letter_text %>
                                <% end %>
                                </div>
                            <!--    < student_id = @student.tracking_id %>-->
                            <!--    < active_session = CoachingSession.where(:status => true).take.name %>-->
                            <!--    < Tracking.create(:session => active_session,:tracking_id => :student_id,:name => @student.name,:accepted => true) %>-->
                            </div>
                              <div class="sf-check">
                                    <label><input type="checkbox" value="test" name="test" data-required="true"><span></span> I acknowledge that I have read all the instructions and conditions stated in my NOP SCS 2016 Invitation Letter</label>
                                </div>
                         </li>
                    </ul>
    
                    <ul class="sf-content"> <!-- form step tree --> 
                         <li>
                            <div class="sf_columns column_6">
                                <div id = "utext">
                                <p align = "left">
                                I,&nbsp;&nbsp;<b><%= @student.name %></b>&nbsp;&nbsp; son/daughter of &nbsp;&nbsp;<b><%= @student.father_name %></b> &nbsp;&nbsp;resident of <b><%= @student.address1 %>,<%= @student.address2 %>,<%= @student.address3 %></b>&nbsp;&nbsp;
                                hereby declare that I have read all the rules and general information carefully and will abide by them during my stay at LUMS.
                                </p>
                                </div>
                                <b><p align = "left"><font color="red">NOTE: “Invitation to participants for coaching session will stand cancelled, if confirmation is not received on time”</font></b>
                                <div id = "utext"><p align = "left"><b>ADHERENCE POLICY:</b><br/><br/>
                            Students are expected to fully participate in the program to take full advantage of learning opportunities at LUMS. We advise you to attend all the classes and assessments for the successful completion of your coaching session.<br/><br/>
 
                            “Absenteeism and late arrivals in classes/ assessments will be monitored closely. If a student is found missing up to 2 sessions of any subject or any of the examinations, he/ she will be disqualified from the programme with immediate effect.”<br/><br/>
 

                            </div>
                            
                            <hr/>
                            <div class="sf-check">
                                
                                    <!--<label><input type="checkbox" value="test" name="test" data-required="true"><span></span> I certify that I will adhere to the policies stated in the undertaking</label>-->
                                    <label><input type="checkbox" value="test" name="test" data-required="true"><span></span> I certify that I will adhere to the policies stated in the undertaking. My parents and I confirm my acceptance to attend the NOP Summer Coaching Session 2016 starting on Monday, 18th July 2016.</label>
                            </div>
                         </li>
                    </ul>
                    <% if @student.boarder == true %>
                    <ul class="sf-content"> <!-- form step four --> 
                     
                    <li>
                            <div class="sf_columns column_6">
                                Download Fee Voucher<br/><br/>
                                <%= link_to "Download Fee Voucher", student_path(@student, format: "pdf"), target: "_blank", :class => "btn btn-primary", :role => "button" %> 
                                <hr/>Upload Fee Receipt<br/><br/>
                                <%= link_to "Upload Fee Voucher", url_for(:controller => "undertakings", :action => "upload"),  :class => "btn btn-primary", :role => "button"  %>
                                  <%= link_to "View Uploaded Fee Voucher", url_for(:controller => "undertakings", :action => "displayfile", id: Student.where(:username => current_user.email).take.tracking_id),target: "_blank",  :class => "btn btn-primary", :role => "button"  %>
                            
                            </div>
                     </li>
                     </ul>
                    <% else %>
                    <ul class="sf-content">
                    As you are from Lahore, you don't need to submit any fee voucher. Please click on "Submit Undertaking" and then Log out.<br/><br/>
                    <%= link_to "Submit Undertaking", url_for(:controller => "undertakings", :action => "day_scholar", id: Student.where(:username => current_user.email).take.tracking_id),  :class => "btn btn-primary", :role => "button"  %>
                    </ul>
                    <% end %>
                    
                    
                </div>
                
                <div class="sf-steps-navigation sf-align-right">
                	<span id="sf-msg" class="sf-msg-error"></span>
                	<button id="sf-prev" type="button" class="sf-button">Previous</button>
                    <button id="sf-next" type="button" class="sf-button ">Next</button>
                </div>
            </form>
        </div>
        <!--STEPS FORM END -------------- -->
		
        
        <div class="footers">
          <div id = "ptext">
            <b>  In case of any query contact the following personnel before the deadline 
Sadia Babar: 042-35608262/ Sharjeel Muazzam: 042-35608438/ Momin Sharif: 042-35608000 (Ext. 2419)/ Shajia Shoaib: 042-35608204
</b>
          </div>
          
       </div>
        
    </div>

<script>
	$(document).ready(function(e) {
       	
		$(".stepsForm").stepsForm({
			theme:'purple'
		}); 
		
		$(".container .themes>span").click(function(e) {
			$(".container .themes>span").removeClass("selectedx");
			$(this).addClass("selectedx");
            $(".stepsForm").removeClass().addClass("stepsForm");
			$(".stepsForm").addClass("sf-theme-"+$(this).attr("data-value"));
        });
    });
</script>

<% end %>

app/views/students_home/password_reset.html.erb
<div class="admin-content-con">
  Please note that In case of Successfull Update, you will be automatically logged out of the system. Log in again with your new password.
  <br/><br/>
  <%= bootstrap_form_tag url: '/students_home/reset' do |f| %>
    <%= f.password_field :new_password %>
    <%= f.password_field :confirm_password %>
    <%= f.submit %> and Log Out
  <% end %>
    
</div>

app/views/students_home/profile.html.erb
  <% if @student %>
<div class = "animated fadeIn">
  <div id="dashboard-con">
    <div>
      <div class="dashboard-left-cell">
        <div class="admin-content-con">
          <header class="clearfix">
            <strong><h3 class="pull-left page_title"><%= @student.name %>'s details</h3></strong>
            <div class = " pull-right">
                  <%= link_to "Back", url_for(:controller => "students_home", :action => "index"),  :class => " btn btn-primary", :role => "button"  %>
          </header>
              <strong>Name:</strong>&nbsp;&nbsp;&nbsp;<%= @student.name %><hr/>
              <strong>Tracking ID:</strong>&nbsp;&nbsp;&nbsp;<%= @student.tracking_id %><hr/>
              <strong>Father's Name:</strong>&nbsp;&nbsp;&nbsp;<%= @student.father_name %><hr/>
              <strong>Date of Birth:</strong>&nbsp;&nbsp;&nbsp;<%= @student.DOB %><hr/>
              <strong>Matric Percentage:</strong>&nbsp;&nbsp;&nbsp;<%= @student.matric_percentage %><hr/>
              <strong>O-Level Grades:</strong>&nbsp;&nbsp;&nbsp;<%= @student.o_level_grades %><hr/>
              <strong>Graduation Year:</strong>&nbsp;&nbsp;&nbsp;<%= @student.graduation_year %><hr/>
              <strong>Gender:</strong>&nbsp;&nbsp;&nbsp;<%= @student.gender %><hr/>
              <strong>Address Line 1:</strong>&nbsp;&nbsp;&nbsp;<%= @student.address1 %><hr/>
              <strong>Address Line 2:</strong>&nbsp;&nbsp;&nbsp;<%= @student.address2 %><hr/>
              <strong>Address Line 3:</strong>&nbsp;&nbsp;&nbsp;<%= @student.address3 %><hr/>
              <strong>City:</strong>&nbsp;&nbsp;&nbsp;<%= @student.city %><hr/>
              <strong>District:</strong>&nbsp;&nbsp;&nbsp;<%= @student.district %><hr/>
              <strong>Province:</strong>&nbsp;&nbsp;&nbsp;<%= @student.province %><hr/>
              <strong>Email Address:</strong>&nbsp;&nbsp;&nbsp;<%= @student.email %><hr/>
              <strong>Phone number:</strong>&nbsp;&nbsp;&nbsp;<%= @student.mobile_number %><hr/>
              <strong>Secondary Phone number:</strong>&nbsp;&nbsp;&nbsp;<%= @student.phone_number %><hr/>
              <strong>DataBurj Username:</strong>&nbsp;&nbsp;&nbsp;<%= @student.username %>
      </div>
    </div>
  </div>

</div>
<% end %>